[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.x86_64-pc-windows-msvc]
linker = "link.exe"

[target.x86_64-pc-windows-msvc.env]
RUSTFLAGS = "-Ctarget-feature=+crt-static"
