---
name: "tauri publish"
'on':
  workflow_dispatch: {}

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: macos-latest
            target: x86_64-apple-darwin
            bundles: app,dmg
          - platform: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            bundles: deb,rpm,appimage
          - platform: windows-latest
            target: x86_64-pc-windows-msvc
            bundles: nsis,msi

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - name: Install Dependencies (Ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libwebkit2gtk-4.1-dev \
            libappindicator3-dev \
            librsvg2-dev \
            patchelf \
            libsoup-3.0-dev \
            libjavascriptcoregtk-4.1-dev
      - name: Cargo build
        run: cargo build --target ${{ matrix.target }}
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: >-
            ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: client-__BRANCH__-v__VERSION__
          releaseName: "Spacebar Client v__VERSION__ (__BRANCH__)"
          releaseBody: >
            See the assets to download this version and install.
            The current commit is __SHA__.
          releaseDraft: false
          prerelease: true
          includeDebug: true
          includeRelease: true
          includeUpdaterJson: true
          args: --target ${{ matrix.target }} --bundles ${{ matrix.bundles }}
